name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -version
      - run: mvn -B package --file pom.xml
      - run: pm2 restart RoboFlask --update-env
